### ISSUE TITLE
Redo button not visible in top menu.

### ISSUE THREAD

**Issue by Insti** [oers/reversatile#66]
The latest update has removed the "redo" button from the main 'board' screen.

I like to review played games, and having to open the menu to access the redo button is really annoying.

(This may be related to my screen size? Do you need a screenshot?)

**Comment by oers** [comment]
Yes. Please give me a Screenshot and the size of your screen.
This change is only on the beta channel at the moment. If it is too annoying you could just leave the beta.

**Comment by oers** [comment]
Which version do you have? 1.3.12 should be fine with the buttons on top and on the button.

**Comment by Insti** [comment]
Thanks, I've got 1.3.9 installed from the play store.
My screen is: 720 x 1280 pixels

How do I get in on the beta?

**Comment by oers** [comment]
1.3.9 is the production version with the normal view. Could you please attach a screenshot? I only started to do a new layout on the beta channel. So the normal one should be unchanged and have the redo button at the top.
you can choose to participate in the beta directly in the play store at the bottom of the Reversatile page.

**Comment by Insti** [comment]
Here's a screenshot, you can see only the undo button and the menu dots in the top right.
In a previous version I could also see "redo" and "new game" icons.

![Screenshot_20190707-205524](https://user-images.githubusercontent.com/5096681/60772674-0fde3600-a0fa-11e9-8be2-40751faba71a.png)

**Comment by Insti** [comment]
1.3.12 Screenshot:

Still missing icons in the top menu.
Icons present in the bottom menu :+1: 
But the board is tiny, :-1:  and the disk count is huge :-1: 

![Screenshot_20190707-211253](https://user-images.githubusercontent.com/5096681/60772854-8ed46e00-a0fc-11e9-98b3-8fa0ed2e1b17.png)

**Comment by Insti** [comment]
After usung 1.3.12 for a few days, the bottom navigation is great 👍 
I don't even think about using the top navigation anymore.

**Comment by oers** [comment]
This is fixed on the development branch, right?

**Comment by Insti** [comment]
It looks right on the emulator so it's probably OK.
I've not tried it on a real device yet.

**Comment by oers** [comment]
should be okay on the development branch

**Comment by Insti** [comment]
Confirm fixed on development branch. 👍

**Comment by oers** [comment]
Hope this is still okay after the latest changes
