### ISSUE TITLE
Minimum API level?

### ISSUE THREAD

**Issue by Insti** [oers/reversatile#70]
We're currently have `minSdkVersion 14` 

Can you see from the install stats if anyone is running it on old devices?

How much effort do we want to put into staying compatible?

This page shows the distribution of versions in use on google play recently: https://developer.android.com/about/dashboards/index.html

I can't (after a quick look) get any Android Studio emulator lower than 16 to run.
Leaving the `minSdkVersion` at 14 but only testing on 16 could also be an option.

**Comment by oers** [comment]
According to the play store statistics I have -2 Users on 4.1 (??) and 8 users on 4.4.
We could go to API Level 21 and I willl try to keep the current Version active in the play store.
Alternativelye people can also download an old Verion from github

**Comment by oers** [comment]
@Insti how did you create the vector, where did you find them?
I would like to replace the iconify library completely when going to api level 21.
There are still some references for the menu.

**Comment by oers** [comment]
Fixed with https://github.com/oers/reversatile/pull/73.

**Comment by Insti** [comment]
> @Insti how did you create the vector, where did you find them?

I followed this guide: https://www.homeandlearn.co.uk/android/android_vector_assets.html

But: 
* In my version of Android studion instead of "Material Icon" it says "Clip Art"
* I changed the colour from black to white and adjusted the name to match.

**Comment by oers** [comment]
@Insti thanks! I switched everything to vector images now
