### ISSUE TITLE
Travis CI - Waiting for emulator

### ISSUE THREAD

**Issue by Insti** [oers/reversatile#71]
Is there something I need to do to to enable the emulator to run with travis-CI?

https://travis-ci.org/oers/reversatile/builds/560657494#L5028

My builds seem to stop at this point, and then timeout and fail.

**Comment by Insti** [comment]
Related? https://travis-ci.org/oers/reversatile/builds/560657494#L2029

**Comment by oers** [comment]
This just stopped working this monh without any code changes. I hoped this was a temporary issue and would go away.

**Comment by oers** [comment]
I found this: https://travis-ci.community/t/android-emulators-not-starting-for-the-last-few-days-late-march-2019/2871/10

**Comment by oers** [comment]
Found working builds here: https://travis-ci.com/mikehardy/Anki-Android/builds/119846621/config.
I will try to fix it.
